### ISSUE TITLE
Please view your exceptions.log. D2Bot will close now :(

### ISSUE THREAD

**Issue by Darakuli** [kolton/d2bot-with-kolbot#2424]
Hi, I seem to have an issue with auto muling at first I couldnt get it to work but now ive managed to get the characters muling items however once the Mule is complete instead of the mule exiting the game I keep an error saying "Please view your exceptions.log" And the mule just sits there.

This is the error I am getting in the log file:

`22/04/2020 05:40
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at D2Bot.ItemScreenShot.Take(Item item, Boolean Save)
   at D2Bot.ItemScreenShot.Take(D2Item d2item, Boolean Save)
   at D2Bot.Main.HandleMessage(IntPtr hWnd, String message)
   at D2Bot.Main.<WorkThread>b__57_0()
`

Has anyone else had this issue? Thanks.

**Comment by noah-** [comment]
looks like one of the items has a string that is causing the error, do you know what item is or have a repro?
