### ISSUE TITLE
limedrop error

### ISSUE THREAD

**Issue by bowtieguy87** [kolton/d2bot-with-kolbot#2530]
6/3/2020 2:39 PM
System.Net.HttpListenerException (0x80004005): An operation was attempted on a nonexistent network connection
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at D2Bot.WebServer.ProcessContext(HttpListenerContext context)
   at D2Bot.WebServer.Listen()

**Comment by bowtieguy87** [comment]
what does this mean

**Comment by Daladlad** [comment]
my guess is limedrop is down right now
maybe they are updating it
