### ISSUE TITLE
Using Limedrop Branch with 1.13d

### ISSUE THREAD

**Issue by alphaomega21** [kolton/d2bot-with-kolbot#694]
I have been using the normal version of d2bot and kolbot with a copy of D2BS for 1.13d and I wanted to try Limedrop but it looks like it had diverged enough that it will no longer work with D2BS from 1.13d.

When I try to start clients I get an Access Violation (c0000005) and I get the following error in the exceptions.log.

System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at D2Bot.D2Profile.StopClient()
   at D2Bot.D2Profile.StopThread()
   at D2Bot.Main.HandleAction(D2Profile d2p, ProfileAction pa)
   at D2Bot.Main.<>c__DisplayClass58_0.<WorkThread>b__0()

I'm would like to know if this is an issue with the version of D2BS I'm using or something else. If it is I'm not totally against possibly modifying the current version of D2BS for 1.13d but I would like to know if it's necessary.

Thanks =)

**Comment by noah-** [comment]
unfortunately not possible
