### ISSUE TITLE
please view your exceptions.log file. d2bot# will close now :(

### ISSUE THREAD

**Issue by sunace** [kolton/d2bot-with-kolbot#725]
computer crashed and now get this error when trying to launch d2bot.exe
this is what my exceptions.log file says

System.NullReferenceException: Object reference not set to an instance of an object.
   at D2Bot.Program.LoadProfile(String file)
   at D2Bot.Program.Main()

don't really understand what it means or how to fix

**Comment by DarkHorseDre** [comment]
no idea - Are your profiles still listed correctly? when you open each one, is the information correct?

if so, and if no responses on here, try to download a new copy of the bot and see if you can run d2bot. if you can, your install is corrupted and will be easier to svn update or use the new copy and migrate configs & changes - will take seconds to test!

**Comment by sunace** [comment]
Cant check profiles cause d2bot wont open it happened while the profiles where running and my computer shut down I tried to update with svn and same issue I gave up and just did a brand new svn install had to resetup my keys and profiles which was a pain lol but o well atleast the new install got me back up and running thanks for reply man

**Comment by DarkHorseDre** [comment]
Glad you got it sorted bro - was probably file corruption due to the PC crash.  At least you know how to restore the files quickly!

**Comment by DarkHorseDre** [comment]
yeah i run mine within dropbox so I can access & update files remotely, but also restore files if needed!

**Comment by Kippievdb** [comment]
@mrandros i had it too, my pc froze because of kolbot crashes. 

3 files could be corrupted after that.

Kolbot/data/cdkeys.json
Kolbot/data/profile.json (File had changed after the freeze/crash)
Kolbot/d2bs/d2bs.ini (File was corrupted somehow, with "Null Null Null"etc.)

My solution is to make a copy of these 3 files and when it happens u can replace them with the corrupted files ;)

**Comment by WolfOfWallStD2Jjsp** [comment]
So can I just take my configs and edited shit out then delete the folder n svc it or just try deleting the profiles from the prog then redo them all then configs right ? .. 

I am am ready to punch a strangers kitten in the face haha.. this happened before .. i did re install then i did it again somehow and i think redoing the profiles/configs but wtf that will be like ima good kittens

**Comment by DarkHorseDre** [comment]
you could start from scratch and copy your files over (you would want to compare & merge what you copy of course!) but you may aswell do an svn update/compare and you will find the differences.
e.g. if a certain file is corrupted, you'll see that when you compare them, line by line

**Comment by WolfOfWallStD2Jjsp** [comment]
Yeah I did a CCleaner sweep and then shit got hairy. Restarted comp had bricks for my passwords and no profiles.  I caused issues trying to fix. Then while the reinstall I got another key.  Installed 2 they worked after mfer quit life. The. Had like gotten confused on what install used what key ... 


:::Takes a breath ::: 

I seen in the ccleaner  registry sweep after crash my bors folders then my sandoxie 8 folders with my toons names in the mix. if you he toons gets of toons I think deletedbots broke CCleaner ate em . Thinking my life loaders were also gone was going to just reinstall scratch then things got worse when I was out installer folders on desktop and was a small stop in corner of screen and I dropped it off POOF bnet traded me a poofer still can't find the fucker musta jumped in a junk folder to escape and I had 3 in placed in case this happens. 

Like that's just St my luck . I lost track of cdkey thinking the bot has his personal set of keys shouldn't matter but this shit just happen so ... I wan a scrap it just install 15 d2's . Then forgot about the the compatibility when fresh install at this point I havey sites poi yes at the lady across the street and her cat just wanting to punch it gut and kick her cane but I had an eye appointment so  . That was my night 🖕to the ghost haunting my computer from all cses that I murdered with a lot of rape.
