### ISSUE TITLE
Kolbot Manager : System.OutOfMemoryException

### ISSUE THREAD

**Issue by mrandros** [kolton/d2bot-with-kolbot#740]
I get this message once a day, and it end up freezing my manager, and make it crash. I got plenty of ram, and only 30gb is in use, at highest

My setup is :
CPU: i7-6700 3,40ghz
RAM: 64gb ram

This is the log file, from the crash log: 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.Windows.Forms.Control.get_WindowText()
   at System.Windows.Forms.TextBoxBase.get_WindowText()
   at System.Windows.Forms.TextBoxBase.ScrollToCaret()
   at D2Bot.Main.ConsolePrint(PrintMessage pm, ProfileBase profile)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
D2Bot
    Assembly Version: 18.3.18.100
    Win32 Version: 18.3.18.100
    CodeBase: file:///C:/Users/Administrator/Documents/Dropper/D2Bot.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 4.5.0.0
    Win32 Version: 18.3.18.100
    CodeBase: file:///C:/Users/Administrator/Documents/Dropper/D2Bot.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 18.3.18.100
    CodeBase: file:///C:/Users/Administrator/Documents/Dropper/D2Bot.exe
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Meebey.SmartIrc4net
    Assembly Version: 0.5.0.0
    Win32 Version: 18.3.18.100
    CodeBase: file:///C:/Users/Administrator/Documents/Dropper/D2Bot.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

![dropper manager crash](https://user-images.githubusercontent.com/31767904/48672738-076cc700-eb3a-11e8-86c9-f20fed865c13.png)

**Comment by noah-** [comment]
what is your memory usage of d2bot at the time this happens?

**Comment by mrandros** [comment]
@noah- 
I run a dropper manager, with dropper and muleloggers for a total of 50 active, and another manager, with 200 mfers

Dropper manager: 1447mb memory/ram
Mfer manager: 941mb memory/ram

It's strange that the Dropper manager use almost 50% more, despite the number of profiles running is not even halv the amount, where characters just idle ingame, while mfers run full profile runes

**Comment by mrandros** [comment]
@noah- 
I have no idea tbh. The error box freezes along with the manager after some minutes i guess. Only a few times, when i am watching it while it happends, i managed to copy/paste the error log

My mf manager run for weeks without any crash, and that log should be way longer, as all the mfers is making a lot of lines, due to death, errors, item drop, etc etc. Do you know if there is some changed, from version to version?

Dropper manager: 18.3.18.100
Mf manager: 18.6.15.200

**Comment by noah-** [comment]
i would recommend updating to the latest versions, your dropper manager is old

**Comment by mrandros** [comment]
@noah- 
I'll try that. Did you suspect the console log to be too long, and causing a crash? If so, could i do anything, to either allow it to have a longer log, or to decrease it somehow? It's really strange, as the Mf manager got week long logs without a crash

**Comment by mrandros** [comment]
@noah- 
The console crashed an hour ago, with the new manager, so it ran for 8 hours, before crash :(

**Comment by mrandros** [comment]
Update:

Clearing the console every hour, do not make it last longer. About 8 hours run time, seem to be "maximum"
